### ISSUE TITLE
Investigate Elastic search performance enhancements

### ISSUE THREAD

**Issue by nicklester** [CM-Well/CM-Well#1034]
It has been observed that the most time consuming part of the STP process is executing the cm-well search query to build the source graph - especially when yg / xg parameters are utilised. At present we will query elastic on a per stream element basis. Elastic will perform better if we can execute the same query for a number of stream elements. It may be worth investigating if this gives us a significant uplift in performance, and if so, designing an implementation into the flow.

**Comment by bryaakov** [comment]
unfortunately, this may not really improve anything
