### ISSUE TITLE
Docker Image?

### ISSUE THREAD

**Issue by r-clancy** [CM-Well/CM-Well#1117]
The documentation has a page for [Docker](https://cm-well.github.io/CM-Well/AdvancedTopics/Tools/Tools.UsingCM-WellDocker.html), but the instructions for building the image aren't present (currently it's "Coming Soon").

Can these be added so that we can use Docker to run CM-Well? The instructions for running are [there](https://cm-well.github.io/CM-Well/AdvancedTopics/Tools/Tools.UsingCM-WellDocker.html#operating-cm-well-docker), but aren't of much use without the image instructions.

**Comment by e-orz** [comment]
Hi,
for the time being you can use the unofficial image:
https://hub.docker.com/r/eorz/cm-well

Please see the instructions there how to pull/run this image.
I will appreciate if you will respond whether it worked or not.

Thanks!

**Comment by r-clancy** [comment]
I'm able to get the image working - thanks!
