### ISSUE TITLE
WikiData Import: Illegal Subject Name

### ISSUE THREAD

**Issue by r-clancy** [CM-Well/CM-Well#1121]
I'm trying to import a number of triples from Wikidata and have come across the following error:

```
ryan@thinkpad ~/Downloads $ curl -X POST "http://localhost:9000/_in?format=ntriples" --data-binary @Q76.nt
{"success":false,"error":"illegal subject name: pt.wikinews.org/wiki/Categoria:Barack_Obama"}⏎       
                                                                                                                                                        
ryan@thinkpad ~/Downloads $ grep "pt.wikinews.org/wiki/Categoria:Barack_Obama" Q76.nt
<https://pt.wikinews.org/wiki/Categoria:Barack_Obama> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Article> .
<https://pt.wikinews.org/wiki/Categoria:Barack_Obama> <http://schema.org/about> <http://www.wikidata.org/entity/Q76> .
<https://pt.wikinews.org/wiki/Categoria:Barack_Obama> <http://schema.org/inLanguage> "pt" .
<https://pt.wikinews.org/wiki/Categoria:Barack_Obama> <http://schema.org/isPartOf> <https://pt.wikinews.org/> .
<https://pt.wikinews.org/wiki/Categoria:Barack_Obama> <http://schema.org/name> "Categoria:Barack Obama"@pt .
```

What about this subject name is invalid? Should the constraints on subject names be relaxed (see https://github.com/CM-Well/CM-Well/issues/156)? What kind of pre-processing do I need to do to the data?

**Comment by bryaakov** [comment]
Looks like CM-Well doesn't like the colon character in Subject URIs.
- @r-clancy - for the time being, as a workaround, you can `sed 's/Categoria:/Categoria_/'` (if it won't hurt your use-case too much).
- @dudi3001 - I think we can allow that one, though I'd be careful not allow every character. What do you think?

**Comment by r-clancy** [comment]
Thanks @bryaakov 

I'd vote for allowing the colon, the entire Wikidata `.nt` dump is about 1.3TB so it would be a lot of pre-processing.

**Comment by bryaakov** [comment]
Have we completed testing this item?

**Comment by MoriaYechiel** [comment]
Yep
