### ISSUE TITLE
Backup solution - Restore mechanism

### ISSUE THREAD

**Issue by YoniMataraso** [CM-Well/CM-Well#292]
The data stored in CM-Well is highly valuable to the customers.
CM-Well has a based replication factor of three, meaning, the cluster can recover from a lost of up to two machines at a time automatically.  
Today, in case of a complete disaster, when the whole cluster is down, a recovery can be done by restoring the data from the other data centers using the data center synchronization capability.
In order to reduce latency or network usage, during the restoration process, we would like to support a cold backup capability.
 
The restore tool will use the collected data from the file/disk and recreate the CM-Well cluster.

**Comment by bryaakov** [comment]
included in #291
