### ISSUE TITLE
STP Dashboard enhancement - Alert system

### ISSUE THREAD

**Issue by nicklester** [CM-Well/CM-Well#393]
After a discussion with @AnnaGrebnev , @yanpom , @e-orz a requirement for a STP job alert has been determined.

If STP sensor was not updated within the last 24 hours, then it should be shown in red on the dashboard

**Comment by YoniMataraso** [comment]
One quick comment about this, we should only alert if we are not in "Horizon" state.

**Comment by yanpom** [comment]
Please parameterize the alert timeout

**Comment by nicklester** [comment]
@yanpom PR raised:#1011

**Comment by nicklester** [comment]
reference.conf in spartl processor agent:

sensor-alert-delay = 1 day

**Comment by yanpom** [comment]
Verified and closed
