### ISSUE TITLE
STP - better logging suggestion

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#409]
Currently when STP agent is working, all materialized infotons are written to agents.log
This overloads the log, and it very hard to monitor it progress or errors, especially when several number of agents are running in parallel
What I suggest is to do the following:
agents log - provide statistics on progress per agent - on normal work each 5 minutes (on horizon each 1 minute) - Received/Materlized/Failed + Performance - Infoton/Sec
Stop printing entire infotons in the log (Enable this in DEBUG)
red.log - for each failed infoton to write one liner with infoton name, cause of failure and number of failure
baddata.log (or some other name) will summaries all failed infotons with number of failure from red log
That way we'll be able to monitor the red.log to see how many infotons failed and if needed go to baddata.log and check what was the failure of specific infoton.

**Comment by nicklester** [comment]
- [ ] Stop logging successful infotons in agents.log
- [ ] Add periodic status updates (dashboard info) into agents.log
- [ ] Add failed infotons to red.log
- [ ] Add detail of failure to bad data log

**Comment by yanpom** [comment]
we need to write failed infotons to red.log both _sp and _in. I think there should be a infoton path and the reason of failure in one liner
