### ISSUE TITLE
STP Engine - Low performance on different agent execution

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#463]
Hi following are performance measurement I've performed on various STP agents:
```
Sparql Name | Materilized infotons Amount | Infoton per sec
Currency | 463 | 12.5
Industry | 149 | 1.5
Person | 740000 | 8.5
Deals | 150000 | 8
```

The performance is very low and there is a need to improve it

**Comment by YoniMataraso** [comment]
@nicklester - Let's see if the root cause of this is the Traffic shaping mechanism or something else after we deploy the Viper release.

**Comment by yanpom** [comment]
yes. Closed
