### ISSUE TITLE
tests seem to deadlock

### ISSUE THREAD

**Issue by hochgi** [CM-Well/CM-Well#568]
I had to abort a build that was stuck in jenkins for almost 20 hours:
![screenshot from 2018-03-07 08-19-41](https://user-images.githubusercontent.com/881075/37076897-1948f570-21e1-11e8-833b-f509c2b39caa.png)

it was stuck on:

![screenshot from 2018-03-07 08-23-53](https://user-images.githubusercontent.com/881075/37076909-2b6005d2-21e1-11e8-92b3-701e3a979537.png)

Perhaps scalatest's single threaded ExecutionContext deadlocks on that test.

**Comment by bryaakov** [comment]
not relevant anymore
