### ISSUE TITLE
STP - Enhancement suggestion for better STP engine execution

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#637]
We frequently see that STP is freezing and doesnt progress (the consume infoton numbers doesnt progress). It might be related to a stuck of STP engine which we saw also when it was working stand alone
The suggestion is to monitor consume numbers of agent in dashboard and if one of the sensors didnt reach Horizon and there was no progress in last 30 minutes (should be configurable parameter) to restart the agent and start from latest saved token. Proper message should be written in agent and stdout logs.

**Comment by nicklester** [comment]
@yanpom - I think this was probably down to environmental / circuit breaking issues we have been seeing in PPE and this should go away once PR #747 is merged. I think doing this we are trying to fix symptoms rather than causes. Thoughts?

**Comment by nicklester** [comment]
@yanpom - can you comment on my note above?

**Comment by yanpom** [comment]
Not relevant anymore
