### ISSUE TITLE
STP - Enhancement - There should be option for user to remove the record from zstore

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#720]
As we will want to give STP to user usage, we need to add option to remove the record from zstore
I dont think that user should do purge on zstore record
Saying that I suggest that there will be some option to do that
We might remove the zstore record automatically if agent is remove or give some other UI option to the user

**Comment by nicklester** [comment]
@yanpom do you think its reasonable to use the zz API for the user to remove tokens if they want to reset?

Removal of agent is also a bit tricky. I fear that if the code to read config infotons fails we could end up deleting tokens and resetting agents etc... Should we not for now document that if the agent is removed you must remove the zstore entry to make sure the end user is really considering what they are doing? I am concerned at the unintended consequences.

**Comment by yanpom** [comment]
I don't want the user to remove it from zstore. I want user to remove the agent itself, with an option to clear the zstore and then we will remove the zstore

**Comment by nicklester** [comment]
@yanpom The problem is, at present, the way you remove the agent is through an API call to remove the config infoton. We can't make this call also to delete from store as the API is generic. 
Do we want to stand back and consider if we want to develop the UI to manage agents ?

Only other option is for STP manager to check what agents are running and remove zstore records for all non running agents. This is dangerous however is the config infotons fail to be read.

**Comment by yanpom** [comment]
We can pass a parameter with purge of agent infoton, which will remove the record from ZZ
Anyway, we need a solution for customer, we wont be able to always control what customer does with STP

**Comment by YoniMataraso** [comment]
After a discussion with @nicklester we suggest the following:
adding a new button to our beloved STP page which will let you remove a token and then will ask if you want to remove data from zstore as well.

Behind the scene this will be implemented as a API call.

**Comment by nicklester** [comment]
@YoniMataraso - can I confirm that you means to "remove a token and then will ask if you want to remove data from zstore as well"

**Comment by YoniMataraso** [comment]
@nicklester exactly what I thought.

**Comment by nicklester** [comment]
@yanpom @YoniMataraso  Quick thought - is it worth having a ui for zz generically so we can remove any object stored in zstore?

**Comment by yanpom** [comment]
Pause/Resume/Reset tokens functionality works
But:
1. Only Root user can do it - we need to change the permissions to any privileged user
2. UI part - on each click another success:true window appears, we should stay on same window, because of the fact that it takes up to 30 sec for change to occur, we need to change immediately from Pause- Pausing, Resume - Resuming, Reset - Reseting and stay on same page while the change occurs.

**Comment by yanpom** [comment]
Verified and closed
