### ISSUE TITLE
STP - stats persistence - Please store the up time of the agent as well

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#781]
Up time of the agent is still cleared on  agent restart

**Comment by YoniMataraso** [comment]
@yanpom I think that this should not be persisted, as this is a way for us to monitor restarts and how long does this process(agent) is running.

**Comment by nicklester** [comment]
@YoniMataraso @yanpom do we want to have both? @YoniMataraso can you let me know so I can close this ticket or progress? Thanks

**Comment by nicklester** [comment]
PR #814 raised

**Comment by YoniMataraso** [comment]
@nicklester - I think that uptime of the agent should be the actual uptime and should not be stored.
