### ISSUE TITLE
https in RDF formatters

### ISSUE THREAD

**Issue by bryaakov** [CM-Well/CM-Well#858]
Since we decided "http == https" (see issues #849 and #854), we must now preserve otherwise the ingested protocol, such that when reading those Infotons in an RDF format - subjects will keep original protocol.

Rather than mangle the Infoton's path by `s"https.$path"`, we will ingest a `protocol` field (nn) to the top-level parent. Those will be cached in WS such that when rendering any Infoton we will be able to know its original protocol.

**Comment by bryaakov** [comment]
https://gist.github.com/bryaakov/16fff50df27259b53b373fc27b831c59

**Comment by Ivan-Shestakov** [comment]
Automated tests covering this feature were added to functional regression suite. Moving to Done.
