### ISSUE TITLE
STP. Infoton rate misleading

### ISSUE THREAD

**Issue by nicklester** [CM-Well/CM-Well#868]
Now that statistics are persisted across restarts of the agent, the infoton rate is completely inaccurate as the calculation will incorporate all infotons previous but only consider the time the agent has run since restart. This leads to wildly inaccurate numbers. I think this figure should show as best as possible a point in time rate - or at least the rate taking into consideration the time since last restart

**Comment by nicklester** [comment]
https://github.com/CM-Well/CM-Well/pull/947

**Comment by nicklester** [comment]
After talking with Yan decided to use one minute moving average

**Comment by yanpom** [comment]
1. Infoton rate name is a bit misleading, i would suggest to change it to Consume/Download Rate
2. Currently agent which is not consuming data at all, still show numbers which are greater then 0. dont quite understand how it is possible, We decided to measure rate once a minute per this minute of work. So I would expect the rate to be 0!
3. As I said we should monitor rate once a minute, but if refreshing the STP dashboard each second on working agent, you would see that the rate changes constantly

**Comment by yanpom** [comment]
Good, but now the Horizon dissapeared

**Comment by nicklester** [comment]
Separate issue - #918

**Comment by yanpom** [comment]
Verified and Closed
