### ISSUE TITLE
Preserve https protocol per Infoton

### ISSUE THREAD

**Issue by bryaakov** [CM-Well/CM-Well#938]
Since we stopped using "https." prefix for Infoton path.
We need to keep it somewhere else, probably as a **new (optional) system field** 😱

Then, **https will be fully supported in all APIs, including _out, _consume etc.**,
_// and we can remove the temp. hack of [wombat-update-3](https://github.com/thomsonreuters/CM-Well/commit/2079cb7182fcdc748d74b200eee5a056ef46d516)_

This will include #858 as well.

**Comment by bryaakov** [comment]
Note on existing data
- if it should be http - nothing needs to be done
- if it should be https - one needs to update the system field, can be done via `_ow` API

**Comment by Ivan-Shestakov** [comment]
Have been tested manually. 
We're still adding automated tests for this feature. 
Moving to Done as of 1.5.164
