### ISSUE TITLE
Enable default RDF Protocol for subjects of existing data Cluster Setting

### ISSUE THREAD

**Issue by bryaakov** [CM-Well/CM-Well#967]
Usage: 

```
val cmw = GridSubDiv(... ,
    defaultRdfProtocol = "https"
)
```

This should be an **optional** field for mappings (default is "http").

This will affect all existing data that was ingested prior to Yak release and has no "protocol" system field to be rendered with that default Cluster setting.

**Comment by bryaakov** [comment]
Related: PR #961

**Comment by Ivan-Shestakov** [comment]
Verified that the option does work. Moving to done.
