### ISSUE TITLE
defaultRdfProtocol isn't persisted correctly in Elastic

### ISSUE THREAD

**Issue by Ivan-Shestakov** [CM-Well/CM-Well#992]
When ingesting mixed bag of infotons and the rdf.defaultProtocol(ws/application.conf) is set to "https" the https infotons don't get the right protocol in Elastic.

Reproduction data is below (5 infotons: 3 https and 2 http paths).
Note this works as expected if rdf.defaultProtocol is set to "http".

1. Set the protocol value to "https" in /opt/cm-well/conf/ws/application.conf for all nodes of the cluster, and restart ws processes.

2. Ingest test data: [testSearchInfotonByProtocolSystemField.txt](https://github.com/CM-Well/CM-Well/files/2598931/testSearchInfotonByProtocolSystemField.txt) with this command `curl cm-well-host/_in?format=ntriples' -d @testSearchInfotonByProtocolSystemField.txt`

3. Execute search query. Expecting 2 results for system.protocol::http and 3 results for system.protocol::https
`http://cm-well-host/test.permid.org/Test201811_18_1419_15/testhttps/testSearchInfotonByProtocolSystemField//?op=search&format=json&qp=system.protocol::http`
Observe that there are 5 results for http and 0 for https.
Examine the https infotons with `?op=x-info` and find out that there is discrepancy between cas and es. In cassandra the protocol is *https* and in elastic *http*

**Comment by bryaakov** [comment]
Can't reproduce in my "pe" :(
Let's try that together tomorrow.

**Comment by Ivan-Shestakov** [comment]
Isn't reproduced on build 63da95504e05b335a75683970c268ca40dc6b7db - probably fixed by one of merges related to https. I'm closing this one.
